name: CD to EC2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Docker Hub sign in
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p "${{secrets.DOCKER_PASSWORD}}"
      - name: Build Docker image
        run: docker build -t gabiliz/pageturner .
      - name: Push Docker image
        run: docker push gabiliz/pageturner
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull gabiliz/pageturner:latest
      - name: Remove Docker container
        run: docker rm -f pageturner
      - name: Run Docker container
        run: docker run -d -p 80:80 -e PORT=80 --name pageturner gabiliz/pageturner